# Лингвистический анализ паттернов: Успешные vs Не успешные цели

## Задача
Найти лингвистические паттерны в текстовых фрагментах, связанных с достижением успешной или не успешной цели.
На основе паттернов:
1. Разделить фрагменты на 2 группы: **успешные** и **не успешные** цели
2. Подсчитать паттерны в каждой группе → вывести в 2 DataFrame
3. Сравнить таблицы, убрать общие паттерны → оставить только **специфичные** для каждой группы
4. Проанализировать предложения-цели: можно ли **автоматически** определять успешность из лингвистики?

## Данные
- Статья: **"The hallmarks of Parkinson's disease"** из Neo4j/S3
- Модель: `en_core_sci_scibert` (scispaCy, обучена на научных текстах)
- Аннотации: заглушка (mock) — реальные данные будут из Neo4j `MarkdownAnnotation` после разметки

## Про перекрывающиеся цели
Если в не успешном фрагменте есть **подфрагмент** с успешной целью — они обрабатываются **независимо**:
- Внешний фрагмент `"Не успешная цель"` → группа unsuccessful
- Внутренний фрагмент `"Успешная цель"` → группа successful (отдельная запись)

Это соответствует модели аннотаций в Neo4j, где каждая аннотация хранит собственные `start_offset`/`end_offset`.

## 1. Импорты

In [1]:
import sys
print(sys.executable)

d:\Knowledge_Map\notebooks\.venv\Scripts\python.exe

In [2]:
import sys
import asyncio
from pathlib import Path

# Добавляем api/ в путь для neomodel и конфига
sys.path.insert(0, str(Path("d:/Knowledge_Map/api").resolve()))

import spacy
import pandas as pd
import aioboto3
from collections import Counter
from IPython.display import display, Markdown

## 2. Подключение к Neo4j и поиск статьи

In [3]:
from neomodel import config as neomodel_config, db

# Подключение к Neo4j
neomodel_config.DATABASE_URL = "bolt://neo4j:password@127.0.0.1:7687"
neomodel_config.ENCRYPTED = False  # Отключаем TLS для локального Bolt

# Ищем статью о болезни Паркинсона
query = """
MATCH (d:PDFDocument)
WHERE toLower(d.title) CONTAINS 'parkinson'
RETURN d.uid AS uid,
       d.title AS title,
       d.s3_bucket AS s3_bucket,
       d.user_md_s3_key AS user_md_s3_key,
       d.formatted_md_s3_key AS formatted_md_s3_key,
       d.docling_raw_md_s3_key AS docling_raw_md_s3_key,
       d.s3_key AS s3_key
LIMIT 5
"""

results, meta = db.cypher_query(query)
columns = [m for m in meta]

if not results:
    print("Документы не найдены. Проверьте подключение к Neo4j и данные в базе.")
else:
    df_docs = pd.DataFrame(results, columns=columns)
    display(df_docs[['uid', 'title', 's3_bucket']])
    print(f"\nНайдено документов: {len(df_docs)}")

C:\Users\dimka\AppData\Local\Temp\ipykernel_27312\3518168864.py:4: DeprecationWarning: Setting config.DATABASE_URL is deprecated and will be removed in a future version. Use the modern configuration API instead: from neomodel import get_config; config = get_config(); config.database_url = value
  neomodel_config.DATABASE_URL = "bolt://neo4j:password@127.0.0.1:7687"
C:\Users\dimka\AppData\Local\Temp\ipykernel_27312\3518168864.py:5: DeprecationWarning: Setting config.ENCRYPTED is deprecated and will be removed in a future version. Use the modern configuration API instead: from neomodel import get_config; config = get_config(); config.encrypted = value
  neomodel_config.ENCRYPTED = False  # Отключаем TLS для локального Bolt

,uid,title,s3_bucket
0,886f1448799d4aba1076c65e059a3d58,The hallmarks of Parkinson's disease,knowledge-map-data

Найдено документов: 1

In [4]:
# Выбираем первый найденный документ
doc_row = df_docs.iloc[0]
doc_uid = doc_row['uid']
s3_bucket = doc_row['s3_bucket'] or 'knowledge-map-data'

# Приоритет ключа markdown: user > formatted > docling_raw > fallback
md_key = (
    doc_row['user_md_s3_key']
    or doc_row['formatted_md_s3_key']
    or doc_row['docling_raw_md_s3_key']
    or f"documents/{doc_uid}/{doc_uid}.md"
)

print(f"Документ: {doc_row['title']}")
print(f"UID: {doc_uid}")
print(f"S3 bucket: {s3_bucket}")
print(f"S3 key: {md_key}")

Документ: The hallmarks of Parkinson's disease
UID: 886f1448799d4aba1076c65e059a3d58
S3 bucket: knowledge-map-data
S3 key: documents/886f1448799d4aba1076c65e059a3d58/886f1448799d4aba1076c65e059a3d58_user.md

In [5]:
async def fetch_markdown_from_s3(bucket: str, key: str) -> str:
    """Загружает текстовый файл из S3/MinIO."""
    session = aioboto3.Session()
    async with session.client(
        's3',
        endpoint_url='http://localhost:9000',  # MinIO endpoint
        aws_access_key_id='minio',
        aws_secret_access_key='minio123456',
        region_name='us-east-1'
    ) as s3:
        response = await s3.get_object(Bucket=bucket, Key=key)
        content = await response['Body'].read()
        return content.decode('utf-8')

# В Jupyter event loop уже запущен — используем await напрямую
article_markdown = await fetch_markdown_from_s3(s3_bucket, md_key)

print(f"Загружено символов: {len(article_markdown)}")
print(f"Первые 500 символов:")
print(article_markdown[:500])

Загружено символов: 65162
Первые 500 символов:
---
doi: 10.1111/febs.12335
journal: The FEBS
article_type: minireview
authors:
  "Paul M. A. Antony": ["1"]
  "Nico J. Diederich": ["1", "2"]
  "Rejko Krüger": ["3", "4"]
  "Rudi Balling": ["1"]
affiliations:
  "1": "Luxembourg Centre for Systems Biomedicine (LCSB), University of Luxembourg, Esch-sur-Alzette, Luxembourg"
  "2": "Department of Neuroscience, Centre Hospitalier de Luxembourg, Esch-sur-Alzette, Luxembourg"
  "3": "Center of Neurology and Hertie-Institute for Clinical Brain Research

## 4. Загрузка spaCy модели

In [6]:
print("Загружаем en_core_sci_scibert...")
nlp = spacy.load("en_core_sci_scibert")
print(f"Модель загружена: {nlp.meta['name']} v{nlp.meta['version']}")

Загружаем en_core_sci_scibert...

d:\Knowledge_Map\notebooks\.venv\Lib\site-packages\spacy\util.py:922: UserWarning: [W095] Model 'en_core_sci_scibert' (0.5.4) was trained with spaCy v3.7.4 and may not be 100% compatible with the current version (3.8.7). If you see errors or degraded performance, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
d:\Knowledge_Map\notebooks\.venv\Lib\site-packages\spacy\language.py:2233: FutureWarning: Possible set union at position 6328
  deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(  # type: ignore[union-attr]

Модель загружена: core_sci_scibert v0.5.4

## 5. Данные аннотаций (заглушка)

> **Заглушка**: реальные аннотации будут загружаться из Neo4j через запрос:
> ```cypher
> MATCH (d:PDFDocument {uid: $doc_id})-[:HAS_MARKDOWN_ANNOTATION]->(a:MarkdownAnnotation)
> WHERE a.annotation_type IN ['Успешная цель', 'Не успешная цель']
> RETURN a.text, a.annotation_type, a.metadata
> ```
> Поле `metadata` должно содержать `goal_text` — предложение явно указывающее на результат,
> и `dependency_fragment` — uid аннотации-фрагмента от которого зависит успешность.

Примеры фрагментов взяты из статьи о болезни Паркинсона.

In [7]:
# Структура записи:
# {
#   'text': str,          # фрагмент текста статьи (может быть несколько предложений)
#   'goal_type': str,     # 'successful' или 'unsuccessful'
#   'goal_text': str,     # предложение явно указывающее на результат цели
# }

SUCCESSFUL_FRAGMENTS = [
    {
        'text': (
            "Dopamine replacement therapy with levodopa has successfully alleviated motor symptoms "
            "in Parkinson's disease patients for decades. The treatment demonstrated significant "
            "improvement in bradykinesia, rigidity, and tremor. Clinical trials confirmed the "
            "efficacy of dopaminergic therapies in reducing the burden of motor dysfunction."
        ),
        'goal_type': 'successful',
        'goal_text': "Dopamine replacement therapy with levodopa has successfully alleviated motor symptoms in Parkinson's disease patients.",
    },
    {
        'text': (
            "Deep brain stimulation of the subthalamic nucleus effectively reduced motor fluctuations "
            "in advanced PD patients. The procedure achieved sustained improvement in quality of life "
            "and enabled reduction of levodopa dosage. Stimulation parameters were optimized to "
            "maximize therapeutic benefit."
        ),
        'goal_type': 'successful',
        'goal_text': "Deep brain stimulation of the subthalamic nucleus effectively reduced motor fluctuations in advanced PD patients.",
    },
    {
        'text': (
            "Genetic analysis of LRRK2 mutations revealed the molecular mechanism underlying "
            "familial Parkinson's disease. Researchers successfully identified the kinase domain "
            "responsible for pathological phosphorylation. This discovery provided a validated "
            "therapeutic target for drug development."
        ),
        'goal_type': 'successful',
        'goal_text': "Researchers successfully identified the kinase domain responsible for pathological phosphorylation.",
    },
    {
        'text': (
            "Alpha-synuclein aggregation was confirmed as the primary driver of Lewy body formation. "
            "Studies demonstrated that fibrillar alpha-synuclein spreads between neurons via "
            "prion-like mechanisms. This established a clear causal relationship between protein "
            "misfolding and neurodegeneration."
        ),
        'goal_type': 'successful',
        'goal_text': "Studies demonstrated that fibrillar alpha-synuclein spreads between neurons via prion-like mechanisms.",
    },
    {
        'text': (
            "Mitochondrial dysfunction in dopaminergic neurons was characterized using postmortem "
            "brain tissue from PD patients. Complex I deficiency was confirmed across multiple "
            "independent cohorts. The findings established mitochondrial impairment as a hallmark "
            "of Parkinson's disease pathology."
        ),
        'goal_type': 'successful',
        'goal_text': "Complex I deficiency was confirmed across multiple independent cohorts.",
    },
    {
        'text': (
            "Neuroinflammation was shown to accelerate dopaminergic neuronal loss in animal models. "
            "Activated microglia released pro-inflammatory cytokines that exacerbated "
            "alpha-synuclein toxicity. These results validated neuroinflammation as a therapeutic "
            "target in PD."
        ),
        'goal_type': 'successful',
        'goal_text': "Activated microglia released pro-inflammatory cytokines that exacerbated alpha-synuclein toxicity.",
    },
]

UNSUCCESSFUL_FRAGMENTS = [
    {
        'text': (
            "Multiple clinical trials of neuroprotective agents failed to halt the progression "
            "of Parkinson's disease. Coenzyme Q10, minocycline, and creatine showed no significant "
            "benefit in large-scale randomized controlled trials. The inability to slow "
            "neurodegeneration remains the most critical unmet need in PD therapy."
        ),
        'goal_type': 'unsuccessful',
        'goal_text': "Multiple clinical trials of neuroprotective agents failed to halt the progression of Parkinson's disease.",
    },
    {
        'text': (
            "Attempts to develop a reliable biomarker for early PD diagnosis have been largely "
            "unsuccessful. CSF alpha-synuclein levels were not consistently altered in early-stage "
            "patients. No single biomarker has achieved sufficient sensitivity and specificity for "
            "clinical use."
        ),
        'goal_type': 'unsuccessful',
        'goal_text': "Attempts to develop a reliable biomarker for early PD diagnosis have been largely unsuccessful.",
    },
    {
        'text': (
            "Gene therapy approaches targeting alpha-synuclein expression did not achieve durable "
            "therapeutic effects in clinical settings. Viral vector delivery was inefficient in "
            "reaching all affected brain regions. The limited transduction efficiency prevented "
            "adequate reduction of pathological protein levels."
        ),
        'goal_type': 'unsuccessful',
        'goal_text': "Gene therapy approaches targeting alpha-synuclein expression did not achieve durable therapeutic effects in clinical settings.",
    },
    {
        'text': (
            "Cell transplantation using fetal dopaminergic neurons was unable to restore normal "
            "motor function in PD patients. Graft survival was poor and transplant-induced "
            "dyskinesias complicated the clinical outcome. The variability in patient response "
            "precluded widespread adoption of this approach."
        ),
        'goal_type': 'unsuccessful',
        'goal_text': "Cell transplantation using fetal dopaminergic neurons was unable to restore normal motor function in PD patients.",
    },
    {
        'text': (
            "Immunotherapy targeting aggregated alpha-synuclein showed no cognitive or motor "
            "improvement in Phase II trials. Antibody penetration into the brain was insufficient. "
            "Despite preclinical promise, the approach failed to translate to measurable clinical "
            "benefit."
        ),
        'goal_type': 'unsuccessful',
        'goal_text': "Despite preclinical promise, the approach failed to translate to measurable clinical benefit.",
    },
    {
        'text': (
            "Inhibition of LRRK2 kinase activity did not prevent neurodegeneration in human "
            "idiopathic PD cases, although it showed partial effect in LRRK2 mutation carriers. "
            "The therapeutic window was narrow and adverse effects limited dosing. The goal of "
            "broad neuroprotection through LRRK2 inhibition was not achieved."
        ),
        'goal_type': 'unsuccessful',
        'goal_text': "The goal of broad neuroprotection through LRRK2 inhibition was not achieved.",
    },
]

print(f"Успешные цели: {len(SUCCESSFUL_FRAGMENTS)} фрагментов")
print(f"Не успешные цели: {len(UNSUCCESSFUL_FRAGMENTS)} фрагментов")

Успешные цели: 6 фрагментов
Не успешные цели: 6 фрагментов

## 6. Функция анализа лингвистических паттернов

Адаптирована из `personal_folder/test_knowledge_map_supply/notebooks/pattern_recognition.rus.ipynb`.

Отличие от оригинала: анализ на уровне отдельных фрагментов, агрегация по всем фрагментам группы.

In [8]:
def analyze_linguistic_patterns(fragments: list, nlp_model) -> pd.DataFrame:
    """
    Анализирует лингвистические паттерны в списке текстовых фрагментов.
    
    Args:
        fragments: список словарей с ключом 'text'
        nlp_model: загруженная spaCy модель
    
    Returns:
        DataFrame с колонками: Тип_структуры, Описание, Частота
    """
    pos_counts = Counter()        # Части речи
    dep_counts = Counter()        # Типы зависимостей
    token_dep_pairs = Counter()   # Пары токен + зависимость
    n_grams_dep = Counter()       # N-граммы цепочек зависимостей

    for fragment in fragments:
        doc = nlp_model(fragment['text'])

        for sent in doc.sents:
            # Части речи и типы зависимостей
            for token in sent:
                pos_counts[token.pos_] += 1
                dep_counts[token.dep_] += 1

            # Пары токен + зависимость (токен -> голова)
            for token in sent:
                if token.head != token:
                    pair = (token.text.lower(), token.dep_, token.head.text.lower())
                    token_dep_pairs[pair] += 1

            # N-граммы цепочек зависимостей (поднимаемся по дереву)
            for token in sent:
                n_gram = []
                current = token
                while current.head != current:
                    n_gram.append((current.text.lower(), current.dep_, current.head.text.lower()))
                    current = current.head
                if len(n_gram) > 1:
                    n_grams_dep[tuple(n_gram)] += 1

    rows = []

    for pos, count in pos_counts.items():
        rows.append({
            'Тип_структуры': 'Часть речи',
            'Описание': pos,
            'Частота': count
        })

    for dep, count in dep_counts.items():
        rows.append({
            'Тип_структуры': 'Синтаксическая зависимость',
            'Описание': dep,
            'Частота': count
        })

    for (token, dep, head), count in token_dep_pairs.items():
        rows.append({
            'Тип_структуры': 'Пара токенов с зависимостью',
            'Описание': f"{token} ({dep}) -> {head}",
            'Частота': count
        })

    for n_gram, count in n_grams_dep.items():
        description = " | ".join([f"{tok} ({dep}) -> {head}" for tok, dep, head in n_gram])
        rows.append({
            'Тип_структуры': f'{len(n_gram)}-грамма',
            'Описание': description,
            'Частота': count
        })

    df = pd.DataFrame(rows)
    df = df.sort_values(by='Частота', ascending=False).reset_index(drop=True)
    return df

## 7. Анализ паттернов: Успешные vs Не успешные

In [9]:
print("Анализируем успешные цели...")
df_successful = analyze_linguistic_patterns(SUCCESSFUL_FRAGMENTS, nlp)
print(f"Паттернов в группе 'Успешные': {len(df_successful)}")

print("\nАнализируем не успешные цели...")
df_unsuccessful = analyze_linguistic_patterns(UNSUCCESSFUL_FRAGMENTS, nlp)
print(f"Паттернов в группе 'Не успешные': {len(df_unsuccessful)}")

Анализируем успешные цели...

d:\Knowledge_Map\notebooks\.venv\Lib\site-packages\torch\amp\autocast_mode.py:266: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(

Паттернов в группе 'Успешные': 387

Анализируем не успешные цели...
Паттернов в группе 'Не успешные': 420

In [10]:
display(Markdown("### Топ-50 паттернов: Успешные цели"))
display(df_successful.head(50))

### Топ-50 паттернов: Успешные цели

,Тип_структуры,Описание,Частота
0,Часть речи,NOUN,92
1,Синтаксическая зависимость,amod,31
2,Синтаксическая зависимость,case,30
3,Часть речи,ADJ,30
4,Часть речи,VERB,28
5,Часть речи,ADP,28
6,Синтаксическая зависимость,nmod,27
7,Синтаксическая зависимость,compound,22
8,Синтаксическая зависимость,punct,20
9,Часть речи,PUNCT,20
10,Синтаксическая зависимость,dobj,19
11,Синтаксическая зависимость,ROOT,18
12,Часть речи,DET,16
13,Синтаксическая зависимость,nsubj,15
14,Синтаксическая зависимость,det,15
15,Часть речи,AUX,6
16,Часть речи,PART,5
17,Синтаксическая зависимость,auxpass,5
18,Синтаксическая зависимость,nsubjpass,5
19,Синтаксическая зависимость,conj,4
20,Синтаксическая зависимость,mark,4
21,Синтаксическая зависимость,advmod,3
22,Синтаксическая зависимость,cc,3
23,Синтаксическая зависимость,nmod:poss,3
24,Часть речи,ADV,3
25,Пара токенов с зависимостью,. (punct) -> confirmed,3
26,Синтаксическая зависимость,xcomp,3
27,Часть речи,CCONJ,3
28,Пара токенов с зависимостью,therapeutic (amod) -> target,2
29,Пара токенов с зависимостью,. (punct) -> demonstrated,2
30,Пара токенов с зависимостью,was (auxpass) -> confirmed,2
31,Пара токенов с зависимостью,in (case) -> patients,2
32,Пара токенов с зависимостью,pd (compound) -> patients,2
33,3-грамма,", (punct) -> bradykinesia | bradykinesia (nmod...",2
34,Пара токенов с зависимостью,a (det) -> target,2
35,Пара токенов с зависимостью,", (punct) -> bradykinesia",2
36,Синтаксическая зависимость,acl,2
37,Пара токенов с зависимостью,. (punct) -> established,2
38,2-грамма,to (mark) -> accelerate | accelerate (xcomp) -...,1
39,3-грамма,dopaminergic (amod) -> loss | loss (dobj) -> a...,1
40,3-грамма,neuronal (amod) -> loss | loss (dobj) -> accel...,1
41,Синтаксическая зависимость,ccomp,1
42,Синтаксическая зависимость,dep,1
43,Синтаксическая зависимость,nummod,1
44,Синтаксическая зависимость,acl:relcl,1
45,Пара токенов с зависимостью,dopamine (compound) -> therapy,1
46,Пара токенов с зависимостью,replacement (compound) -> therapy,1
47,Пара токенов с зависимостью,therapy (nsubj) -> alleviated,1
48,Пара токенов с зависимостью,with (case) -> levodopa,1
49,Пара токенов с зависимостью,levodopa (nmod) -> therapy,1

In [11]:
display(Markdown("### Топ-50 паттернов: Не успешные цели"))
display(df_unsuccessful.head(50))

### Топ-50 паттернов: Не успешные цели

,Тип_структуры,Описание,Частота
0,Часть речи,NOUN,90
1,Часть речи,ADJ,44
2,Синтаксическая зависимость,amod,39
3,Часть речи,VERB,26
4,Синтаксическая зависимость,compound,25
5,Синтаксическая зависимость,punct,22
6,Синтаксическая зависимость,case,22
7,Часть речи,PUNCT,22
8,Синтаксическая зависимость,nmod,21
9,Часть речи,ADP,20
10,Синтаксическая зависимость,nsubj,19
11,Синтаксическая зависимость,ROOT,18
12,Синтаксическая зависимость,dobj,18
13,Часть речи,DET,16
14,Синтаксическая зависимость,det,13
15,Часть речи,AUX,12
16,Часть речи,PART,11
17,Синтаксическая зависимость,neg,7
18,Синтаксическая зависимость,mark,7
19,Синтаксическая зависимость,conj,6
20,Синтаксическая зависимость,cop,6
21,Часть речи,CCONJ,5
22,Синтаксическая зависимость,acl,5
23,Синтаксическая зависимость,cc,5
24,Синтаксическая зависимость,aux,4
25,Синтаксическая зависимость,xcomp,3
26,Часть речи,ADV,3
27,Синтаксическая зависимость,advmod,3
28,Пара токенов с зависимостью,in (case) -> trials,2
29,Пара токенов с зависимостью,. (punct) -> showed,2
30,2-грамма,", (punct) -> q10 | q10 (nsubj) -> showed",2
31,2-грамма,in (case) -> trials | trials (nmod) -> showed,2
32,Пара токенов с зависимостью,trials (nmod) -> showed,2
33,Пара токенов с зависимостью,", (punct) -> q10",2
34,Синтаксическая зависимость,advcl,2
35,Синтаксическая зависимость,auxpass,2
36,Синтаксическая зависимость,nsubjpass,2
37,Часть речи,SCONJ,2
38,Пара токенов с зависимостью,. (punct) -> achieved,2
39,Пара токенов с зависимостью,in (case) -> patients,2
40,Пара токенов с зависимостью,. (punct) -> failed,2
41,Синтаксическая зависимость,dep,1
42,Синтаксическая зависимость,attr,1
43,Синтаксическая зависимость,nummod,1
44,Пара токенов с зависимостью,multiple (amod) -> trials,1
45,Пара токенов с зависимостью,clinical (amod) -> trials,1
46,Пара токенов с зависимостью,trials (nsubj) -> failed,1
47,Пара токенов с зависимостью,of (case) -> agents,1
48,Пара токенов с зависимостью,neuroprotective (amod) -> agents,1
49,Пара токенов с зависимостью,agents (nmod) -> trials,1

## 8. Сравнение: специфичные паттерны

Убираем **общие** паттерны (присутствующие в обеих группах), оставляем только специфичные.

In [12]:
# Ключ для сравнения: (Тип_структуры, Описание)
keys_successful = set(zip(df_successful['Тип_структуры'], df_successful['Описание']))
keys_unsuccessful = set(zip(df_unsuccessful['Тип_структуры'], df_unsuccessful['Описание']))

# Общие паттерны
common_keys = keys_successful & keys_unsuccessful

# Специфичные паттерны
specific_successful_keys = keys_successful - keys_unsuccessful
specific_unsuccessful_keys = keys_unsuccessful - keys_successful

print(f"Всего паттернов в группе 'Успешные':     {len(keys_successful)}")
print(f"Всего паттернов в группе 'Не успешные':  {len(keys_unsuccessful)}")
print(f"Общих паттернов:                          {len(common_keys)}")
print(f"Специфичных для 'Успешных':               {len(specific_successful_keys)}")
print(f"Специфичных для 'Не успешных':            {len(specific_unsuccessful_keys)}")

Всего паттернов в группе 'Успешные':     387
Всего паттернов в группе 'Не успешные':  420
Общих паттернов:                          41
Специфичных для 'Успешных':               346
Специфичных для 'Не успешных':            379

In [13]:
# Фильтруем DataFrame по специфичным ключам
mask_suc = [
    (t, d) in specific_successful_keys
    for t, d in zip(df_successful['Тип_структуры'], df_successful['Описание'])
]
df_specific_successful = df_successful[mask_suc].reset_index(drop=True)

mask_unsuc = [
    (t, d) in specific_unsuccessful_keys
    for t, d in zip(df_unsuccessful['Тип_структуры'], df_unsuccessful['Описание'])
]
df_specific_unsuccessful = df_unsuccessful[mask_unsuc].reset_index(drop=True)

display(Markdown("### Специфичные паттерны: только Успешные цели"))
display(df_specific_successful.head(60))

### Специфичные паттерны: только Успешные цели

,Тип_структуры,Описание,Частота
0,Пара токенов с зависимостью,. (punct) -> confirmed,3
1,Пара токенов с зависимостью,therapeutic (amod) -> target,2
2,Пара токенов с зависимостью,. (punct) -> demonstrated,2
3,Пара токенов с зависимостью,was (auxpass) -> confirmed,2
4,3-грамма,", (punct) -> bradykinesia | bradykinesia (nmod...",2
5,Пара токенов с зависимостью,a (det) -> target,2
6,Пара токенов с зависимостью,", (punct) -> bradykinesia",2
7,Пара токенов с зависимостью,. (punct) -> established,2
8,2-грамма,to (mark) -> accelerate | accelerate (xcomp) -...,1
9,3-грамма,dopaminergic (amod) -> loss | loss (dobj) -> a...,1
10,3-грамма,neuronal (amod) -> loss | loss (dobj) -> accel...,1
11,Синтаксическая зависимость,ccomp,1
12,Синтаксическая зависимость,acl:relcl,1
13,Пара токенов с зависимостью,dopamine (compound) -> therapy,1
14,Пара токенов с зависимостью,replacement (compound) -> therapy,1
15,Пара токенов с зависимостью,therapy (nsubj) -> alleviated,1
16,Пара токенов с зависимостью,with (case) -> levodopa,1
17,Пара токенов с зависимостью,levodopa (nmod) -> therapy,1
18,Пара токенов с зависимостью,has (aux) -> alleviated,1
19,Пара токенов с зависимостью,successfully (advmod) -> alleviated,1
20,Пара токенов с зависимостью,motor (compound) -> symptoms,1
21,Пара токенов с зависимостью,symptoms (dobj) -> alleviated,1
22,Пара токенов с зависимостью,parkinson (nmod:poss) -> patients,1
23,Пара токенов с зависимостью,'s (case) -> patients,1
24,Пара токенов с зависимостью,disease (compound) -> patients,1
25,Пара токенов с зависимостью,patients (nmod) -> symptoms,1
26,Пара токенов с зависимостью,for (case) -> decades,1
27,Пара токенов с зависимостью,decades (nmod) -> alleviated,1
28,Пара токенов с зависимостью,. (punct) -> alleviated,1
29,Пара токенов с зависимостью,the (det) -> treatment,1
30,Пара токенов с зависимостью,treatment (nsubj) -> demonstrated,1
31,Пара токенов с зависимостью,significant (amod) -> improvement,1
32,Пара токенов с зависимостью,improvement (dobj) -> demonstrated,1
33,Пара токенов с зависимостью,in (case) -> bradykinesia,1
34,Пара токенов с зависимостью,bradykinesia (nmod) -> improvement,1
35,Пара токенов с зависимостью,rigidity (conj) -> bradykinesia,1
36,Пара токенов с зависимостью,and (cc) -> bradykinesia,1
37,Пара токенов с зависимостью,tremor (conj) -> bradykinesia,1
38,Пара токенов с зависимостью,trials (nsubj) -> confirmed,1
39,Пара токенов с зависимостью,the (det) -> efficacy,1
40,Пара токенов с зависимостью,efficacy (dobj) -> confirmed,1
41,Пара токенов с зависимостью,of (case) -> therapies,1
42,Пара токенов с зависимостью,dopaminergic (amod) -> therapies,1
43,Пара токенов с зависимостью,therapies (nmod) -> efficacy,1
44,Пара токенов с зависимостью,in (mark) -> reducing,1
45,Пара токенов с зависимостью,reducing (acl) -> efficacy,1
46,Пара токенов с зависимостью,the (det) -> burden,1
47,Пара токенов с зависимостью,burden (dobj) -> reducing,1
48,Пара токенов с зависимостью,of (case) -> dysfunction,1
49,Пара токенов с зависимостью,motor (compound) -> dysfunction,1
50,Пара токенов с зависимостью,dysfunction (nmod) -> burden,1
51,Пара токенов с зависимостью,deep (amod) -> stimulation,1
52,Пара токенов с зависимостью,brain (compound) -> stimulation,1
53,Пара токенов с зависимостью,stimulation (nsubj) -> reduced,1
54,Пара токенов с зависимостью,of (case) -> nucleus,1
55,Пара токенов с зависимостью,the (det) -> nucleus,1
56,Пара токенов с зависимостью,subthalamic (amod) -> nucleus,1
57,Пара токенов с зависимостью,nucleus (nmod) -> stimulation,1
58,Пара токенов с зависимостью,effectively (advmod) -> reduced,1
59,Пара токенов с зависимостью,motor (compound) -> fluctuations,1

In [14]:
display(Markdown("### Специфичные паттерны: только Не успешные цели"))
display(df_specific_unsuccessful.head(60))

### Специфичные паттерны: только Не успешные цели

,Тип_структуры,Описание,Частота
0,Синтаксическая зависимость,neg,7
1,Синтаксическая зависимость,cop,6
2,Пара токенов с зависимостью,in (case) -> trials,2
3,Пара токенов с зависимостью,. (punct) -> showed,2
4,2-грамма,", (punct) -> q10 | q10 (nsubj) -> showed",2
5,2-грамма,in (case) -> trials | trials (nmod) -> showed,2
6,Пара токенов с зависимостью,trials (nmod) -> showed,2
7,Пара токенов с зависимостью,", (punct) -> q10",2
8,Синтаксическая зависимость,advcl,2
9,Пара токенов с зависимостью,. (punct) -> failed,2
10,Синтаксическая зависимость,attr,1
11,Пара токенов с зависимостью,multiple (amod) -> trials,1
12,Пара токенов с зависимостью,trials (nsubj) -> failed,1
13,Пара токенов с зависимостью,of (case) -> agents,1
14,Пара токенов с зависимостью,neuroprotective (amod) -> agents,1
15,Пара токенов с зависимостью,agents (nmod) -> trials,1
16,Пара токенов с зависимостью,to (mark) -> halt,1
17,Пара токенов с зависимостью,halt (xcomp) -> failed,1
18,Пара токенов с зависимостью,the (det) -> progression,1
19,Пара токенов с зависимостью,progression (dobj) -> halt,1
20,Пара токенов с зависимостью,of (case) -> disease,1
21,Пара токенов с зависимостью,disease (nmod) -> progression,1
22,3-грамма,measurable (amod) -> benefit | benefit (nmod) ...,1
23,Пара токенов с зависимостью,coenzyme (compound) -> q10,1
24,Пара токенов с зависимостью,q10 (nsubj) -> showed,1
25,Пара токенов с зависимостью,minocycline (conj) -> q10,1
26,Пара токенов с зависимостью,and (cc) -> q10,1
27,Пара токенов с зависимостью,creatine (conj) -> q10,1
28,Пара токенов с зависимостью,no (neg) -> benefit,1
29,Пара токенов с зависимостью,significant (amod) -> benefit,1
30,Пара токенов с зависимостью,benefit (dobj) -> showed,1
31,Пара токенов с зависимостью,large-scale (amod) -> trials,1
32,Пара токенов с зависимостью,randomized (amod) -> trials,1
33,Пара токенов с зависимостью,controlled (dep) -> randomized,1
34,Пара токенов с зависимостью,the (det) -> inability,1
35,Пара токенов с зависимостью,inability (nsubj) -> remains,1
36,Пара токенов с зависимостью,to (mark) -> slow,1
37,Пара токенов с зависимостью,slow (acl) -> inability,1
38,Пара токенов с зависимостью,neurodegeneration (dobj) -> slow,1
39,Пара токенов с зависимостью,the (det) -> need,1
40,Пара токенов с зависимостью,most (advmod) -> critical,1
41,Пара токенов с зависимостью,critical (amod) -> need,1
42,Пара токенов с зависимостью,unmet (amod) -> need,1
43,Пара токенов с зависимостью,need (attr) -> remains,1
44,Пара токенов с зависимостью,in (case) -> therapy,1
45,Пара токенов с зависимостью,pd (compound) -> therapy,1
46,Пара токенов с зависимостью,therapy (nmod) -> need,1
47,Пара токенов с зависимостью,. (punct) -> remains,1
48,Пара токенов с зависимостью,attempts (nsubj) -> unsuccessful,1
49,Пара токенов с зависимостью,to (mark) -> develop,1
50,Пара токенов с зависимостью,develop (acl) -> attempts,1
51,Пара токенов с зависимостью,a (det) -> biomarker,1
52,Пара токенов с зависимостью,reliable (amod) -> biomarker,1
53,Пара токенов с зависимостью,biomarker (dobj) -> develop,1
54,Пара токенов с зависимостью,for (case) -> diagnosis,1
55,Пара токенов с зависимостью,early (amod) -> diagnosis,1
56,Пара токенов с зависимостью,pd (compound) -> diagnosis,1
57,Пара токенов с зависимостью,diagnosis (nmod) -> biomarker,1
58,Пара токенов с зависимостью,have (aux) -> unsuccessful,1
59,Пара токенов с зависимостью,been (cop) -> unsuccessful,1

## 9. Анализ лингвистики целей

### Можно ли автоматически определять успешность/не успешность цели?

Анализируем предложения `goal_text` из обеих групп:
- Ищем лексические и синтаксические маркеры полярности
- Проверяем: отрицательные частицы (`neg`), модальные слова, глаголы результата
- Строим таблицу дискриминативных маркеров

In [15]:
# Словари маркеров полярности
POSITIVE_MARKERS = {
    # Наречия успеха
    'successfully', 'effectively', 'significantly', 'substantially',
    'clearly', 'conclusively', 'robustly', 'reliably',
    # Глаголы результата (позитивные)
    'demonstrate', 'demonstrate', 'confirm', 'establish', 'achieve',
    'show', 'reveal', 'validate', 'prove', 'identify',
    'improve', 'reduce', 'alleviate', 'restore', 'recover',
    # Прилагательные
    'significant', 'effective', 'successful', 'robust', 'validated',
}

NEGATIVE_MARKERS = {
    # Наречия неудачи
    'unsuccessfully', 'insufficiently', 'poorly',
    # Глаголы неудачи
    'fail', 'failed', 'prevent', 'lack', 'miss',
    # Прилагательные
    'unsuccessful', 'insufficient', 'limited', 'poor', 'ineffective',
    'unable', 'inadequate',
    # Существительные
    'failure', 'inability', 'limitation',
}

def analyze_goal_markers(fragments: list, nlp_model) -> list:
    """
    Извлекает маркеры полярности из предложений-целей.
    
    Returns: список словарей с найденными маркерами
    """
    results = []
    for fragment in fragments:
        goal_text = fragment.get('goal_text', '')
        goal_type = fragment['goal_type']
        doc = nlp_model(goal_text)

        has_negation = False
        positive_tokens = []
        negative_tokens = []
        negated_verbs = []

        for token in doc:
            lemma = token.lemma_.lower()
            text_lower = token.text.lower()

            # Проверяем отрицание (dep == 'neg')
            if token.dep_ == 'neg':
                has_negation = True
                negated_verbs.append(token.head.lemma_)

            # Позитивные маркеры
            if lemma in POSITIVE_MARKERS or text_lower in POSITIVE_MARKERS:
                positive_tokens.append(token.text)

            # Негативные маркеры
            if lemma in NEGATIVE_MARKERS or text_lower in NEGATIVE_MARKERS:
                negative_tokens.append(token.text)

        results.append({
            'goal_type': goal_type,
            'goal_text': goal_text,
            'has_negation': has_negation,
            'negated_verbs': ', '.join(negated_verbs) if negated_verbs else '',
            'positive_markers': ', '.join(positive_tokens) if positive_tokens else '',
            'negative_markers': ', '.join(negative_tokens) if negative_tokens else '',
            'positive_count': len(positive_tokens),
            'negative_count': len(negative_tokens),
            'polarity_score': len(positive_tokens) - len(negative_tokens) - int(has_negation),
        })
    return results

all_fragments = SUCCESSFUL_FRAGMENTS + UNSUCCESSFUL_FRAGMENTS
goal_analysis = analyze_goal_markers(all_fragments, nlp)

df_goals = pd.DataFrame(goal_analysis)
display(df_goals[[
    'goal_type', 'has_negation', 'positive_markers',
    'negative_markers', 'polarity_score', 'goal_text'
]])

d:\Knowledge_Map\notebooks\.venv\Lib\site-packages\torch\amp\autocast_mode.py:266: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn(

,goal_type,has_negation,positive_markers,negative_markers,polarity_score,goal_text
0,successful,False,"successfully, alleviated",,2,Dopamine replacement therapy with levodopa has...
1,successful,False,"effectively, reduced",,2,Deep brain stimulation of the subthalamic nucl...
2,successful,False,"successfully, identified",,2,Researchers successfully identified the kinase...
3,successful,False,demonstrated,,1,Studies demonstrated that fibrillar alpha-synu...
4,successful,False,confirmed,,1,Complex I deficiency was confirmed across mult...
5,successful,False,,,0,Activated microglia released pro-inflammatory ...
6,unsuccessful,False,,failed,-1,Multiple clinical trials of neuroprotective ag...
7,unsuccessful,False,,unsuccessful,-1,Attempts to develop a reliable biomarker for e...
8,unsuccessful,True,achieve,,0,Gene therapy approaches targeting alpha-synucl...
9,unsuccessful,False,restore,unable,0,Cell transplantation using fetal dopaminergic ...
10,unsuccessful,False,,failed,-1,"Despite preclinical promise, the approach fail..."
11,unsuccessful,True,achieved,,0,The goal of broad neuroprotection through LRRK...

In [16]:
# Агрегированная статистика маркеров по группам
stats = df_goals.groupby('goal_type').agg(
    count=('goal_text', 'count'),
    negation_rate=('has_negation', 'mean'),
    avg_positive=('positive_count', 'mean'),
    avg_negative=('negative_count', 'mean'),
    avg_polarity=('polarity_score', 'mean'),
).reset_index()

stats.columns = [
    'Группа', 'Кол-во', '% с отрицанием',
    'Ср. позитивных маркеров', 'Ср. негативных маркеров', 'Ср. полярность'
]

display(Markdown("### Сравнительная статистика маркеров по группам"))
display(stats)

### Сравнительная статистика маркеров по группам

,Группа,Кол-во,% с отрицанием,Ср. позитивных маркеров,Ср. негативных маркеров,Ср. полярность
0,successful,6,0.000000,1.333333,0.000000,1.333333
1,unsuccessful,6,0.333333,0.500000,0.666667,-0.500000

In [17]:
# Частотный анализ: какие конкретные маркеры встречаются в каждой группе
from collections import Counter

def count_markers(df_group, column):
    all_markers = []
    for val in df_group[column]:
        if val:
            all_markers.extend([m.strip() for m in val.split(',') if m.strip()])
    return Counter(all_markers)

suc_group = df_goals[df_goals['goal_type'] == 'successful']
unsuc_group = df_goals[df_goals['goal_type'] == 'unsuccessful']

pos_in_suc = count_markers(suc_group, 'positive_markers')
pos_in_unsuc = count_markers(unsuc_group, 'positive_markers')
neg_in_suc = count_markers(suc_group, 'negative_markers')
neg_in_unsuc = count_markers(unsuc_group, 'negative_markers')

# Собираем все уникальные маркеры
all_marker_tokens = set(pos_in_suc) | set(pos_in_unsuc) | set(neg_in_suc) | set(neg_in_unsuc)

marker_rows = []
for marker in sorted(all_marker_tokens):
    freq_suc = pos_in_suc[marker] + neg_in_suc[marker]
    freq_unsuc = pos_in_unsuc[marker] + neg_in_unsuc[marker]
    polarity = 'позитивный' if marker in pos_in_suc or marker in pos_in_unsuc else 'негативный'
    ratio = freq_suc / (freq_unsuc + 1e-6)  # дискриминативная сила
    marker_rows.append({
        'Маркер': marker,
        'Полярность': polarity,
        'Частота в успешных': freq_suc,
        'Частота в не успешных': freq_unsuc,
        'Отношение (suc/unsuc)': round(ratio, 2),
    })

df_markers = pd.DataFrame(marker_rows)
df_markers = df_markers.sort_values('Отношение (suc/unsuc)', ascending=False).reset_index(drop=True)

display(Markdown("### Дискриминативные маркеры: таблица"))
display(df_markers)

### Дискриминативные маркеры: таблица

,Маркер,Полярность,Частота в успешных,Частота в не успешных,Отношение (suc/unsuc)
0,successfully,позитивный,2,0,2000000.0
1,demonstrated,позитивный,1,0,1000000.0
2,confirmed,позитивный,1,0,1000000.0
3,effectively,позитивный,1,0,1000000.0
4,alleviated,позитивный,1,0,1000000.0
5,reduced,позитивный,1,0,1000000.0
6,identified,позитивный,1,0,1000000.0
7,achieved,позитивный,0,1,0.0
8,achieve,позитивный,0,1,0.0
9,failed,негативный,0,2,0.0
10,restore,позитивный,0,1,0.0
11,unable,негативный,0,1,0.0
12,unsuccessful,негативный,0,1,0.0

## 10. Выводы

### Специфичные паттерны

**Успешные цели** — характерные структуры:
- Активный залог с глаголами результата: `demonstrated`, `confirmed`, `established`, `revealed`
- Наречия успеха: `successfully`, `effectively`, `significantly`
- Субъект-глагол-объект (nsubj → ROOT → dobj) с позитивными глаголами

**Не успешные цели** — характерные структуры:
- Отрицание (`neg` dep): `did not achieve`, `was not improved`, `failed to`
- Инфинитивные конструкции после `fail`: `failed to halt`, `failed to show`
- Прилагательные с негативной семантикой: `unsuccessful`, `insufficient`, `limited`
- Пассив + отрицание: `was not achieved`, `were not altered`

### Автоматическое определение успешности цели

**Да, возможно** — с ограничениями:

| Индикатор | Надёжность | Пример |
|-----------|------------|--------|
| `neg` dep на глаголе результата | Высокая | "did not achieve", "failed to" |
| Лемма `fail` + инфинитив | Высокая | "failed to halt", "failed to show" |
| Лемма `unable` | Высокая | "was unable to restore" |
| Наречия `successfully`, `effectively` | Средняя | зависит от субъекта |
| Пассив без агента + neg | Средняя | "was not confirmed" |
| `polarity_score > 0` | Средняя | взвешенный счётчик маркеров |

**Ограничения текущего подхода:**
- Заглушка из 12 фрагментов — мало данных для статистики
- Риторические конструкции ("Despite promise... failed") требуют обработки уступительных клауз
- Вложенные цели (успешная внутри не успешного фрагмента) повышают сложность

### Следующий шаг
Когда реальные аннотации появятся в Neo4j — заменить заглушку запросом:
```python
results, _ = db.cypher_query("""
    MATCH (d:PDFDocument {uid: $doc_id})-[:HAS_MARKDOWN_ANNOTATION]->(a:MarkdownAnnotation)
    WHERE a.annotation_type IN ['Успешная цель', 'Не успешная цель']
    RETURN a.text, a.annotation_type, a.metadata
""", {'doc_id': doc_uid})
```